# *Préambule* {.unnumbered}


L'objectif de ce document est de fournir un support à l'apprentissage de la cartographie thématique avec R. 


**Comment utiliser le manuel**  
Les données utilisées dans ce document sont stockées dans un projet RStudio. 
Vous devez le télécharger puis le décompresser sur votre machine. Il vous sera ensuite possible de tester l'ensemble des manipulations proposées dans ce document au sein du projet **geodata**.  
[Télécharger le projet](https://rcarto.github.io/cartographie_avec_r/geodata.zip){.btn .btn-primary .btn-sm role="button"}  

**Contribution et feedback**  
Vous pouvez nous envoyer vos remarques et suggestions en [postant une *issue*](https://github.com/rCarto/cartographie_avec_r/issues) sur le [dépôt GitHub](https://github.com/rCarto/cartographie_avec_r) de ce document. 


**Contexte**  
Ce manuel a été initialement conçu pour accompagner le cours "Cartographie avec R" 
du Master 2 Géomatique, géodécisionnel, géomarketing et multimédia (G2M) de 
l'Université Paris 8 Vincennes - Saint-Denis. Une version PDF est disponible ici : [{{< fa file-pdf >}}](https://rcarto.github.io/cartographie_avec_r/Cartographie-avec-R.pdf).  
Un deuxième manuel centré sur la géomatique est disponible ici : 
[Géomatique avec R](https://rcarto.github.io/geomatique_avec_r/).



--------
<small>
**Pour citer le document :**     

Giraud, T. et Pecout, H. (2024). Cartographie avec R. https://doi.org/10.5281/zenodo.5905734 

</small>


